
### get all products
GET http://localhost:3000/api/products

### get product by id
GET http://localhost:3000/api/products/30186c31-4a1f-43d8-be37-ca78e3d8b2c8

### create product
POST http://localhost:3000/api/products
Content-Type: application/json

{
    "name": "Zapatillas Nike Air Max 90",
    "description": "Zapatillas Nike Air Max 90.  Color: Blanco.  Talles: 40, 41, 42, 43, 44, 45, 46",
    "categoryClass": "Calzado",
    "price": 88000,
    "discountClass": "Sin descuento"
}

### modify a product (modificaciones completas)(put-idempotente)
PUT http://localhost:3000/api/products/30186c31-4a1f-43d8-be37-ca78e3d8b2c8
Content-Type: application/json

{
    "name": "Anafe Brogas",
    "description": "Cocina de una hornalla.  Funciona a gas butano con carga descartable tradicional",
    "categoryClass": "Camping",
    "price": 51000,
    "discountClass": "15%"
}


### modify a product (modificaciones parciales)
PATCH  http://localhost:3000/api/products/30186c31-4a1f-43d8-be37-ca78e3d8b2c8
Content-Type: application/json

{
    "discountClass": "Sin Descuento"
}

### delete a product
DELETE http://localhost:3000/api/products/30186c31-4a1f-43d8-be37-ca78e3d8b2c8
